<a href="https://www.kaggle.com/code/antoninast/pytorchkaggle-practice-24-09?scriptVersionId=354395241" target="_blank"><img align="left" alt="Kaggle" title="Open in Kaggle" src="https://kaggle.com/static/images/open-in-kaggle.svg"></a>

Імпорт модулів

In [1]:
import torch

# Завдання 1

Перегляньте інформацію про доступні процесори, та виведіть про них інформацію

In [2]:
import torch
print(torch.cuda.is_available())  # True/False

if torch.cuda.is_available():
    print(torch.cuda.device_count())  # Кількість GPU
    print(torch.cuda.get_device_name(0))  # Назва першого GPU

tensor = torch.tensor([1, 2, 3])
print(tensor.device)  # CPU

True
2
Tesla T4
cpu


# Завдання 2
Підключіться до процесора GPU, та знову виведіть інформацію про доступні процесори

# Завдання 3
Створіть випадковий тензор розміру (2, 3). Виведіть інформацію про його:

* розмір
* тип даних
* процесор
* наявність градієнта

In [3]:
tensor = torch.randn(2,3)

In [4]:
tensor

tensor([[-0.7055, -0.6017,  0.7208],
        [ 0.4365, -1.0237,  0.7307]])

In [5]:
tensor.dtype

torch.float32

In [6]:
tensor.shape

torch.Size([2, 3])

In [7]:
tensor.device

device(type='cpu')

# Завдання 4

Створіть 2 тензора розміру 100. Виведіть
* суму векторів
* частку векторів(перед цим замініть один елемент на 0)
* максимальне та мінімальне значення(методи .min() .max())
* середнє значення(метод .mean())
* квадрад різниці
* середнє значення квадрату різниці

In [8]:
tensor1 = torch.randn(100)
tensor2 = torch.randn(100)

In [9]:
tensor1

tensor([ 4.2042e-04, -1.2898e+00,  4.1511e-01, -1.3607e+00,  6.7207e-01,
        -7.0207e-01, -1.7599e+00, -3.4806e-01, -2.9716e-01,  1.0956e+00,
         6.0883e-01, -2.1463e-01, -1.6519e+00,  4.7716e-01, -1.1515e-01,
        -1.4984e+00, -8.4945e-01, -1.3750e+00, -1.2189e+00, -7.6837e-01,
         7.6052e-01,  1.1426e+00, -7.3474e-01,  1.1347e+00,  5.7182e-01,
         6.7198e-01, -9.0260e-01,  3.7375e-01, -1.6376e+00,  1.8060e-01,
        -5.2931e-01, -6.3090e-01,  7.5488e-01, -1.9336e+00,  3.4482e-01,
        -9.2559e-01,  3.9581e-02,  7.2288e-01, -1.2125e+00, -2.3504e+00,
         7.5836e-01, -8.1544e-01,  4.7514e-01,  4.3163e-01,  7.4856e-02,
        -9.7043e-01,  2.9630e-01, -1.1035e-01, -4.6429e-02,  3.1017e-01,
        -1.9271e+00, -5.2810e-01,  2.6184e-01,  9.7176e-01,  5.4166e-02,
         6.0269e-01, -3.7517e-01, -6.5391e-01,  1.4921e-01, -1.8817e+00,
         1.2037e-01, -7.3084e-01,  4.3526e-01, -1.7632e-02, -1.9109e+00,
         1.2042e+00,  1.5426e-01, -1.2371e+00,  3.3

In [10]:
tensor2

tensor([-1.6741e+00,  1.6234e-01, -3.1614e-01, -1.2023e+00, -2.3408e+00,
         8.3978e-01, -4.5377e-01, -1.3004e+00, -1.2650e+00, -4.6394e-01,
        -4.7705e-01, -2.2768e-01,  1.1695e+00, -1.7091e-01, -1.0373e+00,
        -1.9009e+00,  1.1239e+00,  1.2452e+00, -7.5399e-01, -2.0807e+00,
        -6.9103e-01,  1.6900e+00,  9.3777e-01, -9.4927e-01,  4.0406e-01,
        -1.6084e+00, -2.3370e-01,  1.0946e+00, -8.4721e-02,  1.0254e+00,
         1.3360e+00,  5.6799e-01,  1.5096e+00, -2.4349e+00,  2.1503e+00,
        -1.6810e+00,  8.4386e-02,  9.5759e-01, -3.1675e-01,  9.2109e-01,
         1.9858e-01, -8.8993e-01,  3.7205e-04,  7.3035e-01, -1.8411e-01,
         1.6312e+00, -3.9501e-01,  1.5004e+00,  9.7531e-01,  1.0201e+00,
        -5.3219e-01,  1.7757e+00,  2.4726e-01, -7.3257e-01,  5.7657e-01,
         6.2973e-01, -1.1640e+00,  1.1966e-01,  1.5187e+00, -2.5771e-01,
        -8.1158e-01, -2.3049e+00, -9.3677e-02, -1.4505e+00, -3.2415e-02,
        -2.0082e+00, -1.3522e+00, -1.2301e-01, -1.8

In [11]:
tensor_min = tensor.min()
tensor_max = tensor.max()

In [12]:
tensor_sum = tensor1 + tensor2

In [13]:
tensor_mid = tensor.mean()


In [14]:
tensor2[0] = 0
tensor_div = tensor1 / tensor2

In [15]:
tensor_div.mean()

tensor(inf)

In [16]:
tensor_diff = tensor1 - tensor2

In [17]:
tensor_square = tensor_diff ** 2

In [18]:
tensor_square.mean()

tensor(1.9865)

# Завдання 5

У вашому розпорядженні є нейронна мережа, яка прогнозує **орієнтовну ціну квартири** на основі двох **ознак**:

* **площі квартири** (у квадратних метрах);
* **кількості кімнат**.

Вам надано готовий клас `NeuralNetwork` із методом `predict`.

1. Створіть екземпляр класу `NeuralNetwork`, передайте як параметр `device`.
2. За допомогою методу `predict()` визначте прогнозовану ціну квартири, яка:
   * має площу **65 м²**;
   * має **2 кімнати**.
     
3. Для цього створіть тензор із відповідними числами та скористайтесь методом `predict()`.
4. Усі нейромережі очікують дані розміру `(N, K)`, де:
   * `N` — кількість об'єктів, для яких виконується прогноз;
   * `K` — кількість ознак. У цьому випадку їх дві — **площа квартири та кількість кімнат**.

5. Спробуйте скористатись методом `predict()` разом із `torch.no_grad()`:

```python
with torch.no_grad():
    price = model.predict(...)
```

**Завдання:** отримайте прогнозовану ціну квартири та виведіть результат на екран.


In [19]:
import torch


class NeuralNetwork:
    def __init__(self, device="cpu"):
        self.device = device

        self.W = torch.tensor(
            [[3.3, -38.]],
            requires_grad=True,
            device=device
        )

        self.b = torch.tensor(
            [176.],
            requires_grad=True,
            device=device
        )

    def predict(self, X):
        if not isinstance(X, torch.Tensor):
            raise TypeError("X повинен бути об'єктом torch.Tensor.")

        if X.ndim != 2:
            raise ValueError(
                f"Очікується двовимірний тензор, отримано {X.shape}."
            )

        if X.shape[1] != 2:
            raise ValueError(
                f"Очікується 2 ознаки, отримано {X.shape[1]}."
            )

        if not X.is_floating_point():
            raise TypeError(
                "Тензор повинен містити числа з плаваючою комою (float32 або float64)."
            )

        if X.device != self.W.device:
            raise RuntimeError(
                f"X знаходиться на {X.device}, а модель на {self.W.device}."
            )

        return X @ self.W.T + self.b


In [20]:
model = NeuralNetwork(device = 'cuda')

In [21]:
tensor = torch.tensor([65.0,2.0])

In [22]:
tensor1 = tensor1.reshape(50, 2)

In [23]:
tensor1.shape

torch.Size([50, 2])

In [24]:
tensor.shape

torch.Size([2])

In [25]:
tensor1.device

device(type='cpu')

In [26]:
tensor1 = tensor1.to("cuda")

tensor1

tensor([[ 4.2042e-04, -1.2898e+00],
        [ 4.1511e-01, -1.3607e+00],
        [ 6.7207e-01, -7.0207e-01],
        [-1.7599e+00, -3.4806e-01],
        [-2.9716e-01,  1.0956e+00],
        [ 6.0883e-01, -2.1463e-01],
        [-1.6519e+00,  4.7716e-01],
        [-1.1515e-01, -1.4984e+00],
        [-8.4945e-01, -1.3750e+00],
        [-1.2189e+00, -7.6837e-01],
        [ 7.6052e-01,  1.1426e+00],
        [-7.3474e-01,  1.1347e+00],
        [ 5.7182e-01,  6.7198e-01],
        [-9.0260e-01,  3.7375e-01],
        [-1.6376e+00,  1.8060e-01],
        [-5.2931e-01, -6.3090e-01],
        [ 7.5488e-01, -1.9336e+00],
        [ 3.4482e-01, -9.2559e-01],
        [ 3.9581e-02,  7.2288e-01],
        [-1.2125e+00, -2.3504e+00],
        [ 7.5836e-01, -8.1544e-01],
        [ 4.7514e-01,  4.3163e-01],
        [ 7.4856e-02, -9.7043e-01],
        [ 2.9630e-01, -1.1035e-01],
        [-4.6429e-02,  3.1017e-01],
        [-1.9271e+00, -5.2810e-01],
        [ 2.6184e-01,  9.7176e-01],
        [ 5.4166e-02,  6.026

In [27]:
model.predict(tensor1)

tensor([[225.0146],
        [229.0775],
        [204.8966],
        [183.4186],
        [133.3858],
        [186.1650],
        [152.4165],
        [232.5581],
        [225.4475],
        [201.1758],
        [135.0901],
        [130.4553],
        [152.3516],
        [158.8189],
        [163.7329],
        [198.2273],
        [251.9683],
        [212.3103],
        [148.6611],
        [261.3132],
        [209.4891],
        [161.1659],
        [213.1234],
        [181.1710],
        [164.0603],
        [189.7085],
        [139.9373],
        [153.2764],
        [199.6106],
        [247.9969],
        [204.1691],
        [178.1064],
        [123.9344],
        [223.5178],
        [150.3561],
        [229.6515],
        [158.7724],
        [119.6629],
        [174.8198],
        [126.0783],
        [182.1002],
        [198.3376],
        [194.2328],
        [181.0190],
        [234.4135],
        [162.9970],
        [142.9001],
        [182.4594],
        [171.6241],
        [179.5683]],

# **Завдання 6**

У таблиці наведено інформацію про три квартири.

| **Квартира** | **Площа (м²)** | **Кількість кімнат** |
| ------------ | -------------: | -------------------: |
| Квартира 1   |             40 |                    1 |
| Квартира 2   |             60 |                    3 |
| Квартира 3   |             100 |                    2 |

Виконайте наступні кроки:

1. Створіть **три окремі тензори** (`X1`, `X2`, `X3`), кожен з яких містить дані про одну квартиру.
2. За допомогою методу `predict()` обчисліть **прогнозовану ціну** для кожної квартири окремо.
3. Створіть **один тензор** `X` розміру **(3, 2)**, де:
   * кожен рядок відповідає одній квартирі;
   * перший стовпець — площа квартири;
   * другий стовпець — кількість кімнат.

4. За допомогою одного виклику `predict(X)` отримайте **прогнозовану ціну одразу для всіх трьох квартир**.
5. Виведіть розмір тензору з трьома прогнозованими цінами, який ви отримали на кроці 4.
6. Порівняйте результати, отримані окремими викликами `predict()` та одним спільним викликом `predict(X)`.


In [28]:
model = NeuralNetwork(device = 'cuda')

In [29]:
app1 = torch.tensor([40.0,1.0])
app2 = torch.tensor([60.0,3.0])
app3 = torch.tensor([100.0,2.0])

In [30]:
app1 = app1.reshape(1, 2)
app2 = app2.reshape(1, 2)
app3 = app3.reshape(1, 2)

In [31]:
app1.shape
app2.shape
app2.shape

torch.Size([1, 2])

In [32]:
app1 = app1.to("cuda")
app2 = app2.to("cuda")
app3 = app3.to("cuda")

app1


tensor([[40.,  1.]], device='cuda:0')

In [33]:
model.predict(app1)

tensor([[270.]], device='cuda:0', grad_fn=<AddBackward0>)

In [34]:
model.predict(app2)

tensor([[260.]], device='cuda:0', grad_fn=<AddBackward0>)

In [35]:
model.predict(app3)

tensor([[430.]], device='cuda:0', grad_fn=<AddBackward0>)

In [36]:
X = torch.tensor( [[40.0,1.0],
     [60.0,3.0], 
     [100.0,2.0]
    ]
                )

In [37]:
X = X.to("cuda")

In [38]:
model.predict(X)

tensor([[270.],
        [260.],
        [430.]], device='cuda:0', grad_fn=<AddBackward0>)

# Завдання 7

Три квартири були продані, і стали відомі їхні **реальні ціни**.

| Квартира   | Реальна ціна (1000$) |
| ---------- | ---------------: |
| Квартира 1 |           210 |
| Квартира 2 |          310 |
| Квартира 3 |          360 |

Нехай прогноз моделі збережений у змінній `y_pred`, а реальні значення — у `y_true`.

Визначте, **наскільки модель помилилася**, використавши два різних підходи.

### Варіант 1

1. Знайдіть різницю між прогнозованою та реальною ціною (`y_pred - y_true`).
2. Обчисліть середнє значення цієї різниці за допомогою `torch.mean()`.

### Варіант 2

1. Знайдіть різницю між прогнозованою та реальною ціною (`y_pred - y_true`).
2. Позбудьтеся від'ємних значень за допомогою `torch.abs()`.
3. Обчисліть середнє значення отриманих помилок.

### Запитання

1. Який із двох варіантів краще характеризує якість моделі? Поясніть свою відповідь.
2. Напишіть функцію `loss_fn()`, яка реалізує обраний варіант.

```python
def loss_fn(y_pred, y_true):
    """
    Обчислює середню абсолютну помилку (Mean Absolute Error, MAE).

    Параметри:
        y_pred (torch.Tensor): прогнозовані значення моделі.
        y_true (torch.Tensor): реальні (правильні) значення.

    Повертає:
        torch.Tensor: середню абсолютну помилку.
    """
    ...
```




In [39]:
def loss_fn(y_pred, y_true):
    """
    Обчислює середню абсолютну помилку (Mean Absolute Error, MAE).

    Параметри:
        y_pred (torch.Tensor): прогнозовані значення моделі.
        y_true (torch.Tensor): реальні (правильні) значення.

    Повертає:
        torch.Tensor: середню абсолютну помилку.
    """

    MAE =  y_pred - y_true
    MAE_no_min = MAE.abs()
    MAE_new = MAE_no_min.mean()
    return MAE_new


In [40]:
y_true = torch.tensor([210.0, 310.0, 360.0])

In [41]:
y_true = y_true.reshape(3, 1)

In [42]:
y_true = y_true.to("cuda")

In [43]:
y_pred = model.predict(X)

In [44]:
loss_fn(y_pred, y_true)

tensor(60., device='cuda:0', grad_fn=<MeanBackward0>)

# Завдання 8

У вашому розпорядженні є вчитель, який може навчити нейронну мережу робити точніші прогнози **цін на квартири**.

Клас `Teacher` вже реалізований. Під час створення об'єкта необхідно передати модель, яку потрібно навчати:

```python
teacher = Teacher(model)
```

### Завдання

1. Створіть об'єкт класу `Teacher`, передавши йому модель.
2. Виведіть тензор `X`, який містить дані про квартири:
   * площу квартири;
   * кількість кімнат.

3. Виведіть тензор `y_true` з **реальними цінами квартир**.
4. Отримайте прогноз моделі `y_pred`.
5. Виведіть прогнозовані ціни квартир.
6. За допомогою власної функції `loss_fn()` обчисліть помилку моделі.
7. Виведіть значення помилки.
8. Скористайтеся методом `teach()` класу `Teacher`, передавши йому обчислену помилку.
9. Після навчання знову отримайте прогноз `y_pred`.
10. Виведіть нові прогнозовані ціни квартир.
11. Знову обчисліть та виведіть помилку.
12. Зробіть висновок: **чи стала модель прогнозувати ціни квартир точніше після одного кроку навчання?**



In [45]:
import torch


class Teacher:
    def __init__(self, model, lr=0.02):
        """
        Створює вчителя для навчання моделі.

        Параметри:
            model (NeuralNetwork): модель, яку потрібно навчати.
            lr (float): швидкість навчання.
        """
        self.model = model

        self.optimizer = torch.optim.SGD(
            [model.W, model.b],
            lr=lr
        )

    def teach(self, loss):
        """
        Виконує один крок навчання.

        Параметри:
            loss (torch.Tensor): значення функції втрат.
        """
        self.optimizer.zero_grad()
        loss.backward()
        self.optimizer.step()

teacher = Teacher(model)

print("X:")
print(X)


print("ny_true:")
print(y_true)


model.predict(X)


print(f"Початкові прогнозовані ціни: {y_pred}")


loss = loss_fn(y_pred, y_true)

print(f"Початкова помилка: {loss}")

teacher.teach(loss)


model.predict(X)

print(f"Прогнозовані ціни після навчання: {y_pred}")


new_loss = loss_fn(y_pred, y_true)

print(f"Помилка після навчання: {new_loss}")


if new_loss < loss:
    print("Висновок: модель стала прогнозувати ціни квартир точніше після одного кроку навчання.")
else:
    print("Висновок: після одного кроку навчання модель не стала прогнозувати ціни точніше.")


X:
tensor([[ 40.,   1.],
        [ 60.,   3.],
        [100.,   2.]], device='cuda:0')
ny_true:
tensor([[210.],
        [310.],
        [360.]], device='cuda:0')
Початкові прогнозовані ціни: tensor([[270.],
        [260.],
        [430.]], device='cuda:0', grad_fn=<AddBackward0>)
Початкова помилка: 60.0
Прогнозовані ціни після навчання: tensor([[270.],
        [260.],
        [430.]], device='cuda:0', grad_fn=<AddBackward0>)
Помилка після навчання: 60.0
Висновок: після одного кроку навчання модель не стала прогнозувати ціни точніше.


# Завдання 9

Одного кроку навчання недостатньо, щоб модель навчилася добре прогнозувати ціни. Тому повторіть процес навчання **100 разів**.

### Завдання

1. Створіть об'єкт класу `Teacher`, передавши йому модель.
2. Створіть тензор `X`, який містить дані про квартири.
3. Створіть тензор `y_true`, який містить реальні реальні ціни.
4. Створіть цикл, який виконається **100 разів**.
5. На кожній ітерації циклу:
   * отримайте прогноз моделі `y_pred`;
   * обчисліть помилку за допомогою функції `loss_fn()`;
   * виведіть помилку на екран;
   * передайте помилку в метод `teacher.teach()`, щоб виконати один крок навчання.
    
6. Після завершення циклу ще раз отримайте прогноз моделі.
7. Виведіть:
   * прогнозовані заробітні плати;
   * значення функції втрат.
    
8. Порівняйте отримані прогнози з реальними ціни. Зробіть висновок, чи покращилася точність моделі після 100 кроків навчання.
9. Cпробуйте зменшити навчальний крок в `teacher`

In [48]:

teacher = Teacher(model)


X = torch.tensor([
    [40.0, 1.0],
    [60.0, 3.0],
    [100.0, 2.0]
], dtype=torch.float32, device=model.device)


y_true = torch.tensor([
    [210.0],
    [310.0],
    [360.0]
], dtype=torch.float32, device=model.device)



for i in range(100):
    y_pred = model.predict(X)

    
    loss = loss_fn(y_pred, y_true)

    print(f"Крок {i + 1}: помилка = {loss.item():.4f}")

    
    teacher.teach(loss)



y_pred = model.predict(X)


loss = loss_fn(y_pred, y_true)

print(f"\nПрогнозовані ціни після 100 кроків: {y_pred}")


print(f"\nРеальні ціни: {y_true}")


print(f"\nФінальна помилка: {loss.item()}")

print("\nПорівняння:")

for predicted, real in zip(y_pred, y_true):
    print(
        f"Прогноз: {predicted.item():.2f}, "
        f"реальна ціна: {real.item():.2f}"
    )


Крок 1: помилка = 45.7756
Крок 2: помилка = 56.0045
Крок 3: помилка = 52.8867
Крок 4: помилка = 45.3023
Крок 5: помилка = 59.9978
Крок 6: помилка = 45.7733
Крок 7: помилка = 55.9356
Крок 8: помилка = 52.8844
Крок 9: помилка = 45.2334
Крок 10: помилка = 59.9955
Крок 11: помилка = 45.7711
Крок 12: помилка = 55.8667
Крок 13: помилка = 52.8822
Крок 14: помилка = 45.1645
Крок 15: помилка = 59.9933
Крок 16: помилка = 45.7688
Крок 17: помилка = 55.7979
Крок 18: помилка = 52.8799
Крок 19: помилка = 45.0957
Крок 20: помилка = 59.9910
Крок 21: помилка = 45.7666
Крок 22: помилка = 55.7290
Крок 23: помилка = 52.8777
Крок 24: помилка = 45.0268
Крок 25: помилка = 59.9888
Крок 26: помилка = 45.7643
Крок 27: помилка = 55.6601
Крок 28: помилка = 52.8754
Крок 29: помилка = 44.9579
Крок 30: помилка = 59.9866
Крок 31: помилка = 45.7621
Крок 32: помилка = 55.5913
Крок 33: помилка = 52.8732
Крок 34: помилка = 44.8891
Крок 35: помилка = 59.9843
Крок 36: помилка = 45.7599
Крок 37: помилка = 55.5224
Крок 38: п

# Завдання 10

У вашому розпорядженні є нейронна мережа, яка прогнозує **ймовірність дощу**.

Модель використовує три ознаки:

* температура повітря (°C);
* вологість повітря (%);
* швидкість вітру (км/год).

Результатом роботи моделі є **два числа**:

1. ймовірність того, що **дощу не буде**;
2. ймовірність того, що **дощ буде**.

Скористайтеся методом `predict()`, щоб визначити ймовірності для таких погодних умов:

* температура — **20°C**;
* вологість — **80%**;
* швидкість вітру — **15 км/год**.



In [ ]:
import torch


class RainNeuralNetwork:
    def __init__(self, device="cpu"):
        self.device = device

        self.W = torch.tensor(
            [
                [0.03, 0.01, 0.02],
                [0.06, -0.01, 0.08]
            ],
            requires_grad=True,
            device=device
        )

        self.b = torch.tensor(
            [-0.2, -0.3],
            requires_grad=True,
            device=device
        )

    def predict(self, X):
        if not isinstance(X, torch.Tensor):
            raise TypeError("X повинен бути об'єктом torch.Tensor.")

        if X.ndim != 2:
            raise ValueError(
                f"Очікується двовимірний тензор, отримано {X.shape}."
            )

        if X.shape[1] != 3:
            raise ValueError(
                f"Очікується 3 ознаки, отримано {X.shape[1]}."
            )

        if not X.is_floating_point():
            raise TypeError(
                "Тензор повинен містити числа з плаваючою комою."
            )

        if X.device != self.W.device:
            raise RuntimeError(
                f"X знаходиться на {X.device}, а модель на {self.W.device}."
            )

        logits = X @ self.W.T + self.b
        return torch.softmax(logits, dim=1)

# Завдання 11

Метеостанція надала прогноз погоди на **4 дні**.

| День | Температура (°C) | Вологість (%) | Швидкість вітру (км/год) |
| ---- | ---------------: | ------------: | -----------------------: |
| 1    |               30 |            40 |                        5 |
| 2    |               22 |            85 |                       18 |
| 3    |               15 |            95 |                       25 |
| 4    |               28 |            60 |                       10 |

Виконайте наступні кроки:

1. Створіть один тензор `X` розміру **(4, 3)**, де кожен рядок містить дані про один день.

2. За допомогою методу `predict()` отримайте ймовірності для кожного дня `y_pred`.

3. Скористайтеся функцією `torch.argmax(..., dim=1)`, щоб визначити прогноз моделі `result`:

   * `0` — дощу не буде;
   * `1` — дощ буде.

4. Виведіть:

   * тензор із ймовірностями `y_pred`;
   * тензор із прогнозами `result`


# Завдання 12

Метеорологи повідомили, чи справді пішов дощ у кожен із чотирьох днів.

| День | Дощ |
| ---- | :-: |
| 1    |  Ні |
| 2    | Так |
| 3    | Так |
| 4    |  Ні |

Для навчання моделі використайте готову функцію втрат **CrossEntropyLoss** з бібліотеки **PyTorch**.

### Завдання

1. Створіть об'єкт функції втрат:

   ```python
   loss_fn = torch.nn.CrossEntropyLoss()
   ```

2. Створіть об'єкт класу `Teacher`, передавши йому модель.

3. Створіть тензор `X`, який містить погодні умови за всі 4 дні.

4. Створіть тензор `y_true`, який містить правильні відповіді:

   * `0` — дощу не було;
   * `1` — дощ був.

5. Створіть цикл, який виконається **100 разів**.

6. На кожній ітерації циклу:

   * отримайте ймовірності від моделі `y_pred`:
   * обчисліть помилку:
   * виведіть помилку
   * передайте помилку методу `teacher.teach(loss)` для виконання одного кроку навчання.

7. Після завершення циклу ще раз отримайте прогноз моделі.

8. За допомогою функції `torch.argmax(..., dim=1)` отримайте прогноз моделі:

   * `0` — дощу не буде;
   * `1` — дощ буде.

9. Виведіть:

   * ймовірності, отримані від моделі;
   * прогнози моделі (`0` або `1`);
   * правильні відповіді
   * значення функції втра


# Завдання 13

Попробуйте натренувати модель використовуючи функцію втрат, яку ви раніше застосовували для задачі визначення цін на квартири (`torch.nn.MSELoss()`), замість `CrossEntropyLoss`.

Метеорологи повідомили, чи справді пішов дощ у кожен із чотирьох днів.

| День | Дощ |
|------|-----|
| 1    | Ні  |
| 2    | Так |
| 3    | Так |
| 4    | Ні  |

**Завдання**

1. Створіть об'єкт класу `Teacher`, передавши йому модель.
2. Створіть тензор `X`, який містить погодні умови за всі 4 дні.
3. Створіть тензор `y_true` розміром (4, 2), де кожен рядок містить інформацію про те чи йшов дощ в цей день:
   - `[1, 0]` — дощу не було
   - `[0, 1]` — дощ був
   -  формат інший тому що ваша функція вимагає щоб `y_true` та `y_pred` були однакового розміру
4. Створіть цикл, який виконається 100 разів.

На кожній ітерації циклу:
- отримайте ймовірності від моделі `y_pred`;
- обчисліть помилку;
- виведіть помилку;
- передайте помилку методу `teacher.teach(loss)` для виконання одного кроку навчання.

6. Після завершення циклу ще раз отримайте прогноз моделі.
7. За допомогою функції `torch.argmax(..., dim=1)` отримайте прогноз моделі:
   - 0 — дощу не буде;
   - 1 — дощ буде.

**Виведіть:**
- ймовірності, отримані від моделі;
- прогнози моделі (0 або 1);
- правильні відповіді;
- значення функції втрат.
